#ifndef HERO_INPUT_HPP
#define HERO_INPUT_HPP

#include<SDL2/SDL.h>

#include<stdio.h>
#include<stdint.h>

namespace Hero
{
namespace Input
{
    enum Mouse:uint8_t
    {
        Left = 1,
        Middle = 2,
        Right = 3
    };

    enum Key:uint16_t
    {
        KeyCode_UNKNOWN = 0,
        KeyCode_A = 4,
        KeyCode_B = 5,
        KeyCode_C = 6,
        KeyCode_D = 7,
        KeyCode_E = 8,
        KeyCode_F = 9,
        KeyCode_G = 10,
        KeyCode_H = 11,
        KeyCode_I = 12,
        KeyCode_J = 13,
        KeyCode_K = 14,
        KeyCode_L = 15,
        KeyCode_M = 16,
        KeyCode_N = 17,
        KeyCode_O = 18,
        KeyCode_P = 19,
        KeyCode_Q = 20,
        KeyCode_R = 21,
        KeyCode_S = 22,
        KeyCode_T = 23,
        KeyCode_U = 24,
        KeyCode_V = 25,
        KeyCode_W = 26,
        KeyCode_X = 27,
        KeyCode_Y = 28,
        KeyCode_Z = 29,
        KeyCode_1 = 30,
        KeyCode_2 = 31,
        KeyCode_3 = 32,
        KeyCode_4 = 33,
        KeyCode_5 = 34,
        KeyCode_6 = 35,
        KeyCode_7 = 36,
        KeyCode_8 = 37,
        KeyCode_9 = 38,
        KeyCode_0 = 39,
        KeyCode_RETURN = 40,
        KeyCode_ESCAPE = 41,
        KeyCode_BACKSPACE = 42,
        KeyCode_TAB = 43,
        KeyCode_SPACE = 44,
        KeyCode_MINUS = 45,
        KeyCode_EQUALS = 46,
        KeyCode_LEFTBRACKET = 47,
        KeyCode_RIGHTBRACKET = 48,
        KeyCode_BACKSLASH = 49, 
        KeyCode_NONUSHASH = 50, 
        KeyCode_SEMICOLON = 51,
        KeyCode_APOSTROPHE = 52,
        KeyCode_GRAVE = 53, 
        KeyCode_COMMA = 54,
        KeyCode_PERIOD = 55,
        KeyCode_SLASH = 56,
        KeyCode_CAPSLOCK = 57,
        KeyCode_F1 = 58,
        KeyCode_F2 = 59,
        KeyCode_F3 = 60,
        KeyCode_F4 = 61,
        KeyCode_F5 = 62,
        KeyCode_F6 = 63,
        KeyCode_F7 = 64,
        KeyCode_F8 = 65,
        KeyCode_F9 = 66,
        KeyCode_F10 = 67,
        KeyCode_F11 = 68,
        KeyCode_F12 = 69,
        KeyCode_PRINTSCREEN = 70,
        KeyCode_SCROLLLOCK = 71,
        KeyCode_PAUSE = 72,
        KeyCode_INSERT = 73,
        KeyCode_HOME = 74,
        KeyCode_PAGEUP = 75,
        KeyCode_DELETE = 76,
        KeyCode_END = 77,
        KeyCode_PAGEDOWN = 78,
        KeyCode_RIGHT = 79,
        KeyCode_LEFT = 80,
        KeyCode_DOWN = 81,
        KeyCode_UP = 82,
        KeyCode_NUMLOCKCLEAR = 83,
        KeyCode_KP_DIVIDE = 84,
        KeyCode_KP_MULTIPLY = 85,
        KeyCode_KP_MINUS = 86,
        KeyCode_KP_PLUS = 87,
        KeyCode_KP_ENTER = 88,
        KeyCode_KP_1 = 89,
        KeyCode_KP_2 = 90,
        KeyCode_KP_3 = 91,
        KeyCode_KP_4 = 92,
        KeyCode_KP_5 = 93,
        KeyCode_KP_6 = 94,
        KeyCode_KP_7 = 95,
        KeyCode_KP_8 = 96,
        KeyCode_KP_9 = 97,
        KeyCode_KP_0 = 98,
        KeyCode_KP_PERIOD = 99,
        KeyCode_NONUSBACKSLASH = 100, 
        KeyCode_APPLICATION = 101,
        KeyCode_POWER = 102,
        KeyCode_KP_EQUALS = 103,
        KeyCode_F13 = 104,
        KeyCode_F14 = 105,
        KeyCode_F15 = 106,
        KeyCode_F16 = 107,
        KeyCode_F17 = 108,
        KeyCode_F18 = 109,
        KeyCode_F19 = 110,
        KeyCode_F20 = 111,
        KeyCode_F21 = 112,
        KeyCode_F22 = 113,
        KeyCode_F23 = 114,
        KeyCode_F24 = 115,
        KeyCode_EXECUTE = 116,
        KeyCode_HELP = 117,
        KeyCode_MENU = 118,
        KeyCode_SELECT = 119,
        KeyCode_STOP = 120,
        KeyCode_AGAIN = 121,
        KeyCode_UNDO = 122,
        KeyCode_CUT = 123,
        KeyCode_COPY = 124,
        KeyCode_PASTE = 125,
        KeyCode_FIND = 126,
        KeyCode_MUTE = 127,
        KeyCode_VOLUMEUP = 128,
        KeyCode_VOLUMEDOWN = 129,
        KeyCode_KP_COMMA = 133,
        KeyCode_KP_EQUALSAS400 = 134,
        KeyCode_INTERNATIONAL1 = 135,KeyCode_INTERNATIONAL2 = 136,
        KeyCode_INTERNATIONAL3 = 137,
        KeyCode_INTERNATIONAL4 = 138,
        KeyCode_INTERNATIONAL5 = 139,
        KeyCode_INTERNATIONAL6 = 140,
        KeyCode_INTERNATIONAL7 = 141,
        KeyCode_INTERNATIONAL8 = 142,
        KeyCode_INTERNATIONAL9 = 143,
        KeyCode_LANG1 = 144,
        KeyCode_LANG2 = 145,
        KeyCode_LANG3 = 146,
        KeyCode_LANG4 = 147,
        KeyCode_LANG5 = 148,
        KeyCode_LANG6 = 149,
        KeyCode_LANG7 = 150,
        KeyCode_LANG8 = 151,
        KeyCode_LANG9 = 152,
        KeyCode_ALTERASE = 153,
        KeyCode_SYSREQ = 154,
        KeyCode_CANCEL = 155,
        KeyCode_CLEAR = 156,
        KeyCode_PRIOR = 157,
        KeyCode_RETURN2 = 158,
        KeyCode_SEPARATOR = 159,
        KeyCode_OUT = 160,
        KeyCode_OPER = 161,
        KeyCode_CLEARAGAIN = 162,
        KeyCode_CRSEL = 163,
        KeyCode_EXSEL = 164,
        KeyCode_KP_00 = 176,
        KeyCode_KP_000 = 177,
        KeyCode_THOUSANDSSEPARATOR = 178,
        KeyCode_DECIMALSEPARATOR = 179,
        KeyCode_CURRENCYUNIT = 180,
        KeyCode_CURRENCYSUBUNIT = 181,
        KeyCode_KP_LEFTPAREN = 182,
        KeyCode_KP_RIGHTPAREN = 183,
        KeyCode_KP_LEFTBRACE = 184,
        KeyCode_KP_RIGHTBRACE = 185,
        KeyCode_KP_TAB = 186,
        KeyCode_KP_BACKSPACE = 187,
        KeyCode_KP_A = 188,
        KeyCode_KP_B = 189,
        KeyCode_KP_C = 190,
        KeyCode_KP_D = 191,
        KeyCode_KP_E = 192,
        KeyCode_KP_F = 193,
        KeyCode_KP_XOR = 194,
        KeyCode_KP_POWER = 195,
        KeyCode_KP_PERCENT = 196,
        KeyCode_KP_LESS = 197,
        KeyCode_KP_GREATER = 198,
        KeyCode_KP_AMPERSAND = 199,
        KeyCode_KP_DBLAMPERSAND = 200,
        KeyCode_KP_VERTICALBAR = 201,
        KeyCode_KP_DBLVERTICALBAR = 202,
        KeyCode_KP_COLON = 203,
        KeyCode_KP_HASH = 204,
        KeyCode_KP_SPACE = 205,
        KeyCode_KP_AT = 206,
        KeyCode_KP_EXCLAM = 207,
        KeyCode_KP_MEMSTORE = 208,
        KeyCode_KP_MEMRECALL = 209,
        KeyCode_KP_MEMCLEAR = 210,
        KeyCode_KP_MEMADD = 211,
        KeyCode_KP_MEMSUBTRACT = 212,
        KeyCode_KP_MEMMULTIPLY = 213,
        KeyCode_KP_MEMDIVIDE = 214,
        KeyCode_KP_PLUSMINUS = 215,
        KeyCode_KP_CLEAR = 216,
        KeyCode_KP_CLEARENTRY = 217,
        KeyCode_KP_BINARY = 218,
        KeyCode_KP_OCTAL = 219,
        KeyCode_KP_DECIMAL = 220,
        KeyCode_KP_HEXADECIMAL = 221,
        KeyCode_LCTRL = 224,
        KeyCode_LSHIFT = 225,
        KeyCode_LALT = 226,
        KeyCode_LGUI = 227,
        KeyCode_RCTRL = 228,
        KeyCode_RSHIFT = 229,
        KeyCode_RALT = 230,
        KeyCode_RGUI = 231,
        KeyCode_MODE = 257,
        KeyCode_AUDIONEXT = 258,
        KeyCode_AUDIOPREV = 259,
        KeyCode_AUDIOSTOP = 260,
        KeyCode_AUDIOPLAY = 261,
        KeyCode_AUDIOMUTE = 262,
        KeyCode_MEDIASELECT = 263,
        KeyCode_WWW = 264,
        KeyCode_MAIL = 265,
        KeyCode_CALCULATOR = 266,
        KeyCode_COMPUTER = 267,
        KeyCode_AC_SEARCH = 268,
        KeyCode_AC_HOME = 269,
        KeyCode_AC_BACK = 270,
        KeyCode_AC_FORWARD = 271,
        KeyCode_AC_STOP = 272,
        KeyCode_AC_REFRESH = 273,
        KeyCode_AC_BOOKMARKS = 274,
        KeyCode_BRIGHTNESSDOWN = 275,
        KeyCode_BRIGHTNESSUP = 276,
        KeyCode_DISPLAYSWITCH = 277,
        KeyCode_KBDILLUMTOGGLE = 278,
        KeyCode_KBDILLUMDOWN = 279,
        KeyCode_KBDILLUMUP = 280,
        KeyCode_EJECT = 281,
        KeyCode_SLEEP = 282,
        KeyCode_APP1 = 283,
        KeyCode_APP2 = 284,
        KeyCode_AUDIOREWIND = 285,
        KeyCode_AUDIOFASTFORWARD = 286,
    };

    #ifdef ENGINE
        void Init();
        void Delete();
        void Update();
    #endif

    bool keyPressed(Key key);
    bool keyDown(Key key);
    bool keyUp(Key key);

    bool mouseButtonPressed(Mouse button);
    bool mouseButtonDown(Mouse button);
    bool mouseButtonUp(Mouse button);

    void getMousePosition(int *x, int *y);
    void setMousePosition(int x, int y);
}
}

#endif